FROM mysql:8.0.33
LABEL "Project"="CLStats"
LABEL "Author"="Raphael"

ENV MYSQL_ROOT_PASSWORD="clstatsdbpass"
ENV MYSQL_DATABASE="clstats"

#ADD db_backup.sql /docker-entrypoint-initdb.d/db_backup.sql
